version: 2
jobs:
  build:
    docker:
      - image: circleci/node:11.14.0

    working_directory: ~/cicd-circleci

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  test:
    docker:
      - image: circleci/node:11.14.0

    working_directory: ~/cicd-circleci

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: yarn test

      - save_cache:
          paths:
            - coverage
          key: v1-coverage

    update_analysis:

      - run:
          name: Install Sonar Client
          command: |
            wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.2.0.1227-linux.zip
            unzip sonar-scanner-cli-3.2.0.1227-linux.zip
            export SONAR_SCANNER_OPTS="-Xmx2048m"

      - run:
          name: Update Sonar
          command: |
            eval ./sonar-scanner-3.2.0.1227-linux/bin/sonar-scanner   -Dsonar.projectKey=nekst-web \
                                                                                 -Dsonar.organization=weiller-github \
                                                                                 -Dsonar.sources=./src/web/app \
                                                                                 -Dsonar.test.inclusions=src/**/*.spec.js,src/**/*.spec.jsx,src/**/*.test.js,src/**/*.test.jsx \
                                                                                 -Dsonar.javascript.lcov.reportPaths=./coverage/lcov.info \
                                                                                 -Dsonar.binaries=build/classes \
                                                                                 -Dsonar.host.url=https://sonarcloud.io
                                                                                 -Dsonar.login=969bd71056e6d5f5b04efd964cc79171e591a60f

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
      - update_analysis